// Canonical translations for the small set of terms that the translation
// quality audit (see CLAUDE.md) found Google Translate getting wrong over
// and over, across nearly every locale - "State" read as a nation instead
// of a condition, "Save" read as "rescue", "Match" read as a sports match,
// "Disabled" read as a person's disability, and so on. These are short,
// mostly-standalone UI terms (button labels, section titles, feature
// names), which is exactly where a fixed glossary term works well - it
// doesn't help with longer sentences where grammar/word-order is the
// problem, but that's a limitation of glossaries in general, not just this
// one (Google's own Cloud Translation Glossary has the same limitation).
//
// Keys are matched case-insensitively as whole words/phrases against the
// English source string in translate.common.mjs before each Translate API
// call. Language codes match the `lang` field in translate.constant.mjs
// (Google Translate's codes, e.g. 'zh-cn', not the folder name 'zh_CN').
//
// Coverage: built from this project's own multilingual review, not native-
// speaker-verified. Treat as a strong starting point - if a native speaker
// flags an entry as wrong, fix it here rather than in Google Translate's
// output (a wrong glossary entry is at least easy to find and correct once,
// instead of being silently wrong every time the term is re-translated).
//
// Deliberately NOT included: "State Guard" / "Page Guard" as phrases. That's
// not a vocabulary problem - "State" is genuinely ambiguous in English
// itself ("condition" vs "nation"), so 23 hand-picked phrase translations
// would just be papering over an ambiguous source string. Renaming the en/
// source term (e.g. "State Guard" -> "Condition Guard") fixes it at the
// root for every locale at once; see CLAUDE.md.
const GLOSSARY = {
  Automation: {
    'zh-cn': '自动化',
    'zh-tw': '自動化',
    fr: 'Automatisation',
    ko: '자동화',
    sv: 'Automatisering',
    pt: 'Automação',
    ja: '自動化',
    nl: 'Automatisering',
    de: 'Automatisierung',
    es: 'Automatización',
    vi: 'Tự động hóa',
    fi: 'Automaatio',
    ar: 'أتمتة',
    it: 'Automazione',
    ru: 'Автоматизация',
    id: 'Otomatisasi',
    hi: 'स्वचालन',
    bg: 'Автоматизация',
    pl: 'Automatyzacja',
    th: 'ระบบอัตโนมัติ',
    sw: 'Otomatiki',
    fil: 'Awtomasyon',
    kk: 'Автоматтандыру'
  },
  Step: {
    'zh-cn': '步骤',
    'zh-tw': '步驟',
    fr: 'Étape',
    ko: '단계',
    sv: 'Steg',
    pt: 'Etapa',
    ja: 'ステップ',
    nl: 'Stap',
    de: 'Schritt',
    es: 'Paso',
    vi: 'Bước',
    fi: 'Vaihe',
    ar: 'خطوة',
    it: 'Passaggio',
    ru: 'Шаг',
    id: 'Langkah',
    hi: 'चरण',
    bg: 'Стъпка',
    pl: 'Krok',
    th: 'ขั้นตอน',
    sw: 'Hatua',
    fil: 'Hakbang',
    kk: 'Қадам'
  },
  Loop: {
    'zh-cn': '循环',
    'zh-tw': '循環',
    fr: 'Boucle',
    ko: '루프',
    sv: 'Loop',
    pt: 'Loop',
    ja: 'ループ',
    nl: 'Lus',
    de: 'Schleife',
    es: 'Bucle',
    vi: 'Vòng lặp',
    fi: 'Silmukka',
    ar: 'حلقة تكرار',
    it: 'Ciclo',
    ru: 'Цикл',
    id: 'Perulangan',
    hi: 'लूप',
    bg: 'Цикъл',
    pl: 'Pętla',
    th: 'การวนซ้ำ',
    sw: 'Kitanzi',
    fil: 'Loop',
    kk: 'Цикл'
  },
  Save: {
    'zh-cn': '保存',
    'zh-tw': '儲存',
    fr: 'Enregistrer',
    ko: '저장',
    sv: 'Spara',
    pt: 'Salvar',
    ja: '保存',
    nl: 'Opslaan',
    de: 'Speichern',
    es: 'Guardar',
    vi: 'Lưu',
    fi: 'Tallenna',
    ar: 'حفظ',
    it: 'Salva',
    ru: 'Сохранить',
    id: 'Simpan',
    hi: 'सहेजें',
    bg: 'Запази',
    pl: 'Zapisz',
    th: 'บันทึก',
    sw: 'Hifadhi',
    fil: 'I-save',
    kk: 'Сақтау'
  },
  Enable: {
    'zh-cn': '启用',
    'zh-tw': '啟用',
    fr: 'Activer',
    ko: '활성화',
    sv: 'Aktivera',
    pt: 'Ativar',
    ja: '有効にする',
    nl: 'Inschakelen',
    de: 'Aktivieren',
    es: 'Habilitar',
    vi: 'Bật',
    fi: 'Ota käyttöön',
    ar: 'تفعيل',
    it: 'Abilita',
    ru: 'Включить',
    id: 'Aktifkan',
    hi: 'सक्षम करें',
    bg: 'Активирай',
    pl: 'Włącz',
    th: 'เปิดใช้งาน',
    sw: 'Washa',
    fil: 'Paganahin',
    kk: 'Қосу'
  },
  Disable: {
    'zh-cn': '禁用',
    'zh-tw': '停用',
    fr: 'Désactiver',
    ko: '비활성화',
    sv: 'Inaktivera',
    pt: 'Desativar',
    ja: '無効にする',
    nl: 'Uitschakelen',
    de: 'Deaktivieren',
    es: 'Deshabilitar',
    vi: 'Tắt',
    fi: 'Poista käytöstä',
    ar: 'تعطيل',
    it: 'Disabilita',
    ru: 'Отключить',
    id: 'Nonaktifkan',
    hi: 'अक्षम करें',
    bg: 'Деактивирай',
    pl: 'Wyłącz',
    th: 'ปิดใช้งาน',
    sw: 'Zima',
    fil: 'Huwag paganahin',
    kk: 'Өшіру'
  },
  Disabled: {
    'zh-cn': '已禁用',
    'zh-tw': '已停用',
    fr: 'Désactivé',
    ko: '비활성화됨',
    sv: 'Inaktiverad',
    pt: 'Desativado',
    ja: '無効',
    nl: 'Uitgeschakeld',
    de: 'Deaktiviert',
    es: 'Deshabilitado',
    vi: 'Đã tắt',
    fi: 'Poistettu käytöstä',
    ar: 'معطّل',
    it: 'Disabilitato',
    ru: 'Отключено',
    id: 'Dinonaktifkan',
    hi: 'अक्षम',
    bg: 'Деактивирано',
    pl: 'Wyłączone',
    th: 'ปิดใช้งานแล้ว',
    sw: 'Imezimwa',
    fil: 'Naka-disable',
    kk: 'Өшірілген'
  },
  Reorder: {
    'zh-cn': '重新排序',
    'zh-tw': '重新排序',
    fr: 'Réorganiser',
    ko: '순서 변경',
    sv: 'Ordna om',
    pt: 'Reordenar',
    ja: '並べ替え',
    nl: 'Herschikken',
    de: 'Neu anordnen',
    es: 'Reordenar',
    vi: 'Sắp xếp lại',
    fi: 'Järjestä uudelleen',
    ar: 'إعادة الترتيب',
    it: 'Riordina',
    ru: 'Изменить порядок',
    id: 'Atur ulang urutan',
    hi: 'पुनः क्रमबद्ध करें',
    bg: 'Пренареди',
    pl: 'Zmień kolejność',
    th: 'จัดเรียงใหม่',
    sw: 'Panga upya',
    fil: 'Ayusing muli',
    kk: 'Ретін өзгерту'
  },
  // Kept in English everywhere - every locale reviewed mistranslated this as
  // "fast/immediate" and none got the JS prompt() dialog type right, so a
  // fixed English label is safer than guessing per language.
  Prompt: {
    'zh-cn': 'Prompt',
    'zh-tw': 'Prompt',
    fr: 'Prompt',
    ko: 'Prompt',
    sv: 'Prompt',
    pt: 'Prompt',
    ja: 'Prompt',
    nl: 'Prompt',
    de: 'Prompt',
    es: 'Prompt',
    vi: 'Prompt',
    fi: 'Prompt',
    ar: 'Prompt',
    it: 'Prompt',
    ru: 'Prompt',
    id: 'Prompt',
    hi: 'Prompt',
    bg: 'Prompt',
    pl: 'Prompt',
    th: 'Prompt',
    sw: 'Prompt',
    fil: 'Prompt',
    kk: 'Prompt'
  },
  Match: {
    'zh-cn': '匹配',
    'zh-tw': '匹配',
    fr: 'Correspondance',
    ko: '일치',
    sv: 'Träff',
    pt: 'Correspondência',
    ja: '一致',
    nl: 'Overeenkomst',
    de: 'Übereinstimmung',
    es: 'Coincidencia',
    vi: 'Khớp',
    fi: 'Osuma',
    ar: 'تطابق',
    it: 'Corrispondenza',
    ru: 'Совпадение',
    id: 'Kecocokan',
    hi: 'मिलान',
    bg: 'Съвпадение',
    pl: 'Dopasowanie',
    th: 'การจับคู่',
    sw: 'Ulinganifu',
    fil: 'Tugma',
    kk: 'Сәйкестік'
  },
  Monitor: {
    'zh-cn': '监控',
    'zh-tw': '監控',
    fr: 'Surveillance',
    ko: '모니터링',
    sv: 'Övervakning',
    pt: 'Monitoramento',
    ja: '監視',
    nl: 'Monitoring',
    de: 'Überwachung',
    es: 'Monitorización',
    vi: 'Giám sát',
    fi: 'Valvonta',
    ar: 'مراقبة',
    it: 'Monitoraggio',
    ru: 'Мониторинг',
    id: 'Pemantauan',
    hi: 'निगरानी',
    bg: 'Наблюдение',
    pl: 'Monitorowanie',
    th: 'การเฝ้าติดตาม',
    sw: 'Ufuatiliaji',
    fil: 'Monitoring',
    kk: 'Бақылау'
  },
  // Kept in English everywhere - every locale mistranslated this technical
  // term (mute, bounce, deny, detach...) and none got it right.
  Debounce: {
    'zh-cn': 'Debounce',
    'zh-tw': 'Debounce',
    fr: 'Debounce',
    ko: 'Debounce',
    sv: 'Debounce',
    pt: 'Debounce',
    ja: 'Debounce',
    nl: 'Debounce',
    de: 'Debounce',
    es: 'Debounce',
    vi: 'Debounce',
    fi: 'Debounce',
    ar: 'Debounce',
    it: 'Debounce',
    ru: 'Debounce',
    id: 'Debounce',
    hi: 'Debounce',
    bg: 'Debounce',
    pl: 'Debounce',
    th: 'Debounce',
    sw: 'Debounce',
    fil: 'Debounce',
    kk: 'Debounce'
  },
  Stable: {
    'zh-cn': '稳定版',
    'zh-tw': '穩定版',
    fr: 'Stable',
    ko: '안정 버전',
    sv: 'Stabil',
    pt: 'Estável',
    ja: '安定版',
    nl: 'Stabiel',
    de: 'Stabil',
    es: 'Estable',
    vi: 'Ổn định',
    fi: 'Vakaa',
    ar: 'مستقر',
    it: 'Stabile',
    ru: 'Стабильный',
    id: 'Stabil',
    hi: 'स्थिर',
    bg: 'Стабилна',
    pl: 'Stabilna',
    th: 'เสถียร',
    sw: 'Imara',
    fil: 'Matatag',
    kk: 'Тұрақты'
  },
  Visibility: {
    'zh-cn': '可见性',
    'zh-tw': '可見性',
    fr: 'Visibilité',
    ko: '공개 설정',
    sv: 'Synlighet',
    pt: 'Visibilidade',
    ja: '公開設定',
    nl: 'Zichtbaarheid',
    de: 'Sichtbarkeit',
    es: 'Visibilidad',
    vi: 'Chế độ hiển thị',
    fi: 'Näkyvyys',
    ar: 'مستوى الظهور',
    it: 'Visibilità',
    ru: 'Видимость',
    id: 'Visibilitas',
    hi: 'दृश्यता',
    bg: 'Видимост',
    pl: 'Widoczność',
    th: 'การมองเห็น',
    sw: 'Mwonekano',
    fil: 'Visibility',
    kk: 'Көрінуі'
  },
  Timeout: {
    'zh-cn': '超时',
    'zh-tw': '逾時',
    fr: "Délai d'expiration",
    ko: '타임아웃',
    sv: 'Tidsgräns',
    pt: 'Tempo limite',
    ja: 'タイムアウト',
    nl: 'Time-out',
    de: 'Zeitüberschreitung',
    es: 'Tiempo de espera',
    vi: 'Hết thời gian chờ',
    fi: 'Aikakatkaisu',
    ar: 'انتهاء المهلة',
    it: 'Timeout',
    ru: 'Тайм-аут',
    id: 'Waktu habis',
    hi: 'समय समाप्ति',
    bg: 'Таймаут',
    pl: 'Limit czasu',
    th: 'หมดเวลา',
    sw: 'Muda kuisha',
    fil: 'Timeout',
    kk: 'Уақыт аяқталуы'
  },
  Publish: {
    'zh-cn': '发布',
    'zh-tw': '發布',
    fr: 'Publier',
    ko: '게시',
    sv: 'Publicera',
    pt: 'Publicar',
    ja: '公開する',
    nl: 'Publiceren',
    de: 'Veröffentlichen',
    es: 'Publicar',
    vi: 'Đăng',
    fi: 'Julkaise',
    ar: 'نشر',
    it: 'Pubblica',
    ru: 'Опубликовать',
    id: 'Publikasikan',
    hi: 'प्रकाशित करें',
    bg: 'Публикувай',
    pl: 'Opublikuj',
    th: 'เผยแพร่',
    sw: 'Chapisha',
    fil: 'I-publish',
    kk: 'Жариялау'
  },
  Value: {
    'zh-cn': '值',
    'zh-tw': '值',
    fr: 'Valeur',
    ko: '값',
    sv: 'Värde',
    pt: 'Valor',
    ja: '値',
    nl: 'Waarde',
    de: 'Wert',
    es: 'Valor',
    vi: 'Giá trị',
    fi: 'Arvo',
    ar: 'القيمة',
    it: 'Valore',
    ru: 'Значение',
    id: 'Nilai',
    hi: 'मान',
    bg: 'Стойност',
    pl: 'Wartość',
    th: 'ค่า',
    sw: 'Thamani',
    fil: 'Value',
    kk: 'Мән'
  },
  Clear: {
    'zh-cn': '清除',
    'zh-tw': '清除',
    fr: 'Effacer',
    ko: '지우기',
    sv: 'Rensa',
    pt: 'Limpar',
    ja: 'クリア',
    nl: 'Wissen',
    de: 'Löschen',
    es: 'Borrar',
    vi: 'Xóa',
    fi: 'Tyhjennä',
    ar: 'مسح',
    it: 'Cancella',
    ru: 'Очистить',
    id: 'Hapus',
    hi: 'साफ़ करें',
    bg: 'Изчисти',
    pl: 'Wyczyść',
    th: 'ล้าง',
    sw: 'Futa',
    fil: 'I-clear',
    kk: 'Тазарту'
  },
  Downgrade: {
    'zh-cn': '降级',
    'zh-tw': '降級',
    fr: 'Rétrograder',
    ko: '다운그레이드',
    sv: 'Nedgradera',
    pt: 'Fazer downgrade',
    ja: 'ダウングレード',
    nl: 'Downgraden',
    de: 'Herabstufen',
    es: 'Degradar',
    vi: 'Hạ cấp',
    fi: 'Alenna',
    ar: 'خفض المستوى',
    it: 'Declassa',
    ru: 'Понизить',
    id: 'Turunkan',
    hi: 'डाउनग्रेड करें',
    bg: 'Понижи',
    pl: 'Obniż',
    th: 'ลดระดับ',
    sw: 'Punguza',
    fil: 'I-downgrade',
    kk: 'Төмендету'
  },
  // The next three are literal values, not translatable concepts: a CSS
  // selector, HTML attribute names, and a JS/API method identifier. Kept
  // verbatim in every language - translating any of them produces a value
  // that doesn't actually work if a user copies it in (found for real in
  // 15-19 locales: "body" became the literal word for a human body, "class"
  // became "social class", "hidden" became the adjective, etc).
  body: {
    'zh-cn': 'body',
    'zh-tw': 'body',
    fr: 'body',
    ko: 'body',
    sv: 'body',
    pt: 'body',
    ja: 'body',
    nl: 'body',
    de: 'body',
    es: 'body',
    vi: 'body',
    fi: 'body',
    ar: 'body',
    it: 'body',
    ru: 'body',
    id: 'body',
    hi: 'body',
    bg: 'body',
    pl: 'body',
    th: 'body',
    sw: 'body',
    fil: 'body',
    kk: 'body'
  },
  'style, class, hidden': {
    'zh-cn': 'style, class, hidden',
    'zh-tw': 'style, class, hidden',
    fr: 'style, class, hidden',
    ko: 'style, class, hidden',
    sv: 'style, class, hidden',
    pt: 'style, class, hidden',
    ja: 'style, class, hidden',
    nl: 'style, class, hidden',
    de: 'style, class, hidden',
    es: 'style, class, hidden',
    vi: 'style, class, hidden',
    fi: 'style, class, hidden',
    ar: 'style, class, hidden',
    it: 'style, class, hidden',
    ru: 'style, class, hidden',
    id: 'style, class, hidden',
    hi: 'style, class, hidden',
    bg: 'style, class, hidden',
    pl: 'style, class, hidden',
    th: 'style, class, hidden',
    sw: 'style, class, hidden',
    fil: 'style, class, hidden',
    kk: 'style, class, hidden'
  },
  // Branded plan-tier names (with their emoji, exactly as they appear in
  // web.json's plan.*.name fields) - not translatable concepts either, a
  // product name isn't supposed to change per locale. Found for real being
  // machine-translated into ordinary words instead of kept as a name (e.g.
  // "🚀 PLUS" -> "🚀 加", "🔹 PRO" -> "🔹 专业版" in Chinese).
  '🆓 FREE': {
    'zh-cn': '🆓 FREE',
    'zh-tw': '🆓 FREE',
    fr: '🆓 FREE',
    ko: '🆓 FREE',
    sv: '🆓 FREE',
    pt: '🆓 FREE',
    ja: '🆓 FREE',
    nl: '🆓 FREE',
    de: '🆓 FREE',
    es: '🆓 FREE',
    vi: '🆓 FREE',
    fi: '🆓 FREE',
    ar: '🆓 FREE',
    it: '🆓 FREE',
    ru: '🆓 FREE',
    id: '🆓 FREE',
    hi: '🆓 FREE',
    bg: '🆓 FREE',
    pl: '🆓 FREE',
    th: '🆓 FREE',
    sw: '🆓 FREE',
    fil: '🆓 FREE',
    kk: '🆓 FREE'
  },
  '🚀 PLUS': {
    'zh-cn': '🚀 PLUS',
    'zh-tw': '🚀 PLUS',
    fr: '🚀 PLUS',
    ko: '🚀 PLUS',
    sv: '🚀 PLUS',
    pt: '🚀 PLUS',
    ja: '🚀 PLUS',
    nl: '🚀 PLUS',
    de: '🚀 PLUS',
    es: '🚀 PLUS',
    vi: '🚀 PLUS',
    fi: '🚀 PLUS',
    ar: '🚀 PLUS',
    it: '🚀 PLUS',
    ru: '🚀 PLUS',
    id: '🚀 PLUS',
    hi: '🚀 PLUS',
    bg: '🚀 PLUS',
    pl: '🚀 PLUS',
    th: '🚀 PLUS',
    sw: '🚀 PLUS',
    fil: '🚀 PLUS',
    kk: '🚀 PLUS'
  },
  '🔹 PRO': {
    'zh-cn': '🔹 PRO',
    'zh-tw': '🔹 PRO',
    fr: '🔹 PRO',
    ko: '🔹 PRO',
    sv: '🔹 PRO',
    pt: '🔹 PRO',
    ja: '🔹 PRO',
    nl: '🔹 PRO',
    de: '🔹 PRO',
    es: '🔹 PRO',
    vi: '🔹 PRO',
    fi: '🔹 PRO',
    ar: '🔹 PRO',
    it: '🔹 PRO',
    ru: '🔹 PRO',
    id: '🔹 PRO',
    hi: '🔹 PRO',
    bg: '🔹 PRO',
    pl: '🔹 PRO',
    th: '🔹 PRO',
    sw: '🔹 PRO',
    fil: '🔹 PRO',
    kk: '🔹 PRO'
  },
  getElementBy: {
    'zh-cn': 'getElementBy',
    'zh-tw': 'getElementBy',
    fr: 'getElementBy',
    ko: 'getElementBy',
    sv: 'getElementBy',
    pt: 'getElementBy',
    ja: 'getElementBy',
    nl: 'getElementBy',
    de: 'getElementBy',
    es: 'getElementBy',
    vi: 'getElementBy',
    fi: 'getElementBy',
    ar: 'getElementBy',
    it: 'getElementBy',
    ru: 'getElementBy',
    id: 'getElementBy',
    hi: 'getElementBy',
    bg: 'getElementBy',
    pl: 'getElementBy',
    th: 'getElementBy',
    sw: 'getElementBy',
    fil: 'getElementBy',
    kk: 'getElementBy'
  }
};

export { GLOSSARY };
